### ISSUE TITLE
TurboVNC process  survive RCM  window exit

### ISSUE THREAD

**Issue by luigi-calori** [RemoteConnectionManager/RCM#14]
If RCM has an open VNC session, when  main gui window gets closed, VNC remain active but the main RCM process hangs, last message is 
Killing tunnel process--><tunnel process number>
The process does not get properly killed though but goes into defunct state
When the VNC window get closed, both processes exit, the main one errors:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/kubuntu/home/lcalori/spack/test_deploy_dev/RCM/rcm/client/logic/thread.py", line 98, in run
    self.execute_vnc_command_with_internal_ssh_tunnel()
  File "/kubuntu/home/lcalori/spack/test_deploy_dev/RCM/rcm/client/logic/thread.py", line 125, in execute_vnc_command_with_internal_ssh_tunnel
    while self.tunnel_process.poll() is None:
AttributeError: 'NoneType' object has no attribute 'poll'

**Comment by sbna** [comment]
it should be fixed, can you try again?

**Comment by luigi-calori** [comment]
it seems that 6b7f3dc8ad44173adaa4b52914fabddfe3bcd614 close the issue, tested on linux unpached
